apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-global-config
  namespace: healthcare-rpm
data:
  SPRING_PROFILES_ACTIVE: "kubernetes,production"
  EUREKA_SERVER_URL: "http://service-registry:8761/eureka/"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  ELASTICSEARCH_URIS: "http://elasticsearch:9200"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/healthcare-realm"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/healthcare-realm/protocol/openid-connect/certs"

---
apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare-rpm
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgrespassword"
  REDIS_PASSWORD: "redispassword"
  KEYCLOAK_CLIENT_SECRET: "hExghH54qXgHTl3WnNJJ1nCW2dxeRBI1"
  JWT_SIGNING_SECRET: "h3althc4r3-s3cur3-jwt-signing-k3y-2026-v21-spring34"
