apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcare-api-ingress
  namespace: healthcare-rpm
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/plugins: "cors, rate-limiting, correlation-id, prometheus"
spec:
  rules:
    - host: api.healthcare-rpm.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kong-gateway
                port:
                  number: 8000

